# -*- coding: utf-8 -*-
"""LVADSUSR_176_anomaly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXHMED-EIB2x_pSew372WKY5FzwOMDcz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler,StandardScaler , LabelEncoder
from sklearn.cluster import DBSCAN
from sklearn.ensemble import IsolationForest
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

from numpy import loadtxt

from sklearn.cluster import KMeans

from sklearn.metrics import r2_score,mean_squared_error , silhouette_score
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score , confusion_matrix

anom = pd.read_csv('https://raw.githubusercontent.com/Deepsphere-AI/LVA-Batch5-Assessment/main/anomaly_train.csv')
anom.head()

anom.isna().sum()
# No null

anom = anom.drop_duplicates()
anom.shape

anom.info()

anom.describe()

anom["Type"] = LabelEncoder().fit_transform(anom["Type"])
anom["Location"] = LabelEncoder().fit_transform(anom["Location"])

anom.drop(columns = ["TransactionID"],inplace = True)
anom.head()

for i in anom.columns:
  sns.boxplot(anom[i])
  plt.title(i)
  plt.show()

for i in anom.columns:
  plt.hist(anom[i])
  plt.title(i)
  plt.show()

# outliers
print(anom.shape)
for col in ['Amount','Time']:
  q1 = anom[col].quantile(0.25)
  q3 = anom[col].quantile(0.75)
  iqr = q3-q1
  thres = 3
  lower = q1-thres*iqr
  upper = q3+thres*iqr
  mask =  (anom[col] >lower ) & (anom[col] < upper )
  new_df = anom[mask]
print(new_df.shape)

# No Outliers

X = new_df
model = IsolationForest(n_estimators = 100,max_samples = 'auto' ,contamination =0.1 ,random_state = 42)
model.fit(X)
y_pred = model.predict(X)
plt.scatter(X['Amount'],X['User'],c=y_pred)
plt.title('Anomalies')
plt.show()