# -*- coding: utf-8 -*-
"""final-python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jv4Cwv4PpaE3cMkSLfvO1HrD4pcEXeEp
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#1A
ipl = pd.read_csv('/content/Final Dataset - IPL.csv')
ipl.head()

#1B
print("INFO: ",ipl.info())

#2A
print("NA: ", ipl.isna().sum())
# no missing values to handle

#2B

print(len(ipl))
print("count of duplicates",ipl.duplicated().sum())
ipl = ipl.drop_duplicates()
ipl.head()
#there are no duplicates in the data

#3a
des = ipl.describe()
# The avg first innings score is 171 while second is 158
# The standard deviation for the first innings is 29 and second is also around 29

#4a
# histogram
data = ipl[ipl['won_by']=='Runs']
plt.hist(data['margin'], label = 'margin')
plt.xlabel('Margin')
plt.ylabel('Frequency')
plt.title('Frequency of win margin by runs(batting first)')
plt.show()

# Most mathces were close with teams winning with less than 20 runs

#4a
# Bar
data = ipl.groupby('match_winner')['match_winner'].count()
data.plot(kind = 'bar')
plt.xlabel('Team')
plt.ylabel('Wins')
plt.title('Wins of each team')
plt.show()
# Gujrat won the most matches while mumbai and chennai won the least

#4a Scatter

data = ipl[['first_ings_score','first_ings_wkts']]
data.plot(x='first_ings_wkts',y='first_ings_score',kind ='scatter')
data = ipl[['second_ings_score','second_ings_wkts']]
data.plot(x='second_ings_wkts',y='second_ings_score',kind ='scatter')

# We can see as wickets taken increases score declines

# 4a BOX
cols = ['first_ings_score',
       'second_ings_score', 'highscore']
data = ipl[cols]

data.plot(kind='box')
plt.ylabel('score')
plt.xlabel('Type of score')
plt.title('BOX-PLOT')
plt.show()
#  we can observe that the second innings score has a much higher range compared to the first innings

#4a
ipl['toss_and_match'] = (ipl['toss_winner']==ipl['match_winner'])
df = ipl.groupby('toss_and_match')['toss_and_match'].count()
df.plot(kind='pie',autopct='%1.1f%%')
plt.title('Number of teams that won the toss and match')
plt.show()

#5a
ipl['toss_and_match'] = (ipl['toss_winner']==ipl['match_winner'])
df = ipl.groupby('toss_and_match')['toss_and_match'].count()
df.plot(kind='pie',autopct='%1.1f%%')
plt.title('Number of teams that won the toss and match')
plt.show()
# Hence winning the toss has no real impact on winning the game

#5a

data = ipl.groupby(['venue','match_winner'])['match_winner'].count()
data = pd.DataFrame(data)
data
# No team has won more than 2 games ata any given venue hence no advantage by a venue to a team

# #other work
# ipl.head()
# ipl['first_by'] = np.ones(len(ipl))
# for i in range(len(ipl)):
#   if ipl['toss_decision'].iloc[i] == 'Bat':
#     ipl['first_by'].iloc[i] =  ipl['toss_winner'].iloc[i]
#   else:
#     if ipl['team1'].iloc[i] == ipl['toss_winner'].iloc[i]:
#       ipl['first_by'].iloc[i] =  ipl['team2'].iloc[i]
#     else:
#       ipl['first_by'].iloc[i] =  ipl['team1'].iloc[i]


# ipl.head(5)

#6
ipl = ipl[ipl['won_by']=='Runs']

cols = ['first_ings_score', 'first_ings_wkts',
       'second_ings_score', 'second_ings_wkts', 'highscore']
for col in cols:
    x = data[col].mean()
    s = data[col].std()
    # mask = (abs(data[col]) >= x+2*s)
    mask = (abs(data[col]) >= x+3*s)
    x = data[mask]
    print("Outliers in column: ",col,":",x[col])
# No Outliers in any of the numeric columns

#7

# avg highest score in each stadium :
# avg first innings score
# avg second innings score
q7 = ipl.groupby('venue')[['first_ings_score','second_ings_score','highscore']].mean()
q7.plot(kind='bar',label = q7.columns)
plt.title('Average Scores Across Stadiums')
plt.xlabel('Stadium')
plt.ylabel('Score')

# We can observe that the avg scores are higher in Eden Gardens stadium

#7
q7b = ipl.groupby('stage')[['first_ings_score','second_ings_score','highscore']].mean()
q7b.plot(kind='bar',label = q7b.columns)
plt.title('Average Scores Across Stadiums')
plt.xlabel('Stadium')
plt.ylabel('Stage')
# The playoffs had higher score than the league stages on average which shows teams have nothing to lose

#8
play = ipl.groupby('top_scorer')['highscore'].mean()
play.plot(kind = 'bar')
plt.title('Avg score of top scorers')
plt.show()
# Rajat Patidhar has the highest average score when it comes to top scorers

play = ipl.groupby('top_scorer')['highscore'].count()
play.plot(kind = 'bar')
plt.title('Avg times a player had top score')
plt.show()

#8
play = ipl.groupby('player_of_the_match')['player_of_the_match'].count()
play.plot(kind = 'bar')
plt.title('Avg player of the match wins')
plt.show()

#  Only 4 players have won player of the match 2 times

"""9



1.   There is no relation between winning the toss and winning the match
2.   Gujrat titans have won most of the matches in the league stage and hence top the table
3. KL Rahul seems to be one of the most consistent players winning high score 4 times

4. Eden Gardens is a batting friendly ground

5. There has not been any extraordinary score made in the season nor has any team had a landslide victory

6. Most of the games were close matches

7. The more wickets a team loses the less the total score seems to be



"""

