# -*- coding: utf-8 -*-
"""LVADSUSR_176_IA2_Clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_BC5gfAymf35Q04lKy18DbbIbCPJXBsi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import MinMaxScaler,StandardScaler , LabelEncoder
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings('ignore')

from numpy import loadtxt

from sklearn.cluster import KMeans

df = pd.read_csv('/content/Mall_Customers.csv')
df.head()

data = df.dropna()
data = data.drop_duplicates()

lbl = LabelEncoder()
data["Gender"] = lbl.fit_transform(data['Gender'])
data.head()

data.describe()

data.head()

data = data.drop(columns = ['CustomerID'])
data.head()

#  elbow method to find K
scaler = MinMaxScaler()
X = scaler.fit_transform(data)



wcss = []
for i in range(1,10):
  kmeans  = KMeans(n_clusters = i , random_state = 34)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)

plt.plot(range(1,10),wcss)
plt.title("Elbow Graph")
plt.xlabel("N clusters")
plt.ylabel("WCSS")
plt.grid()
plt.show()
# We can see that the elbow is deflected at n = 4 ,

n = 4
kmeans  = KMeans(n_clusters = n , random_state = 34)
kmeans.fit(X)
m = dict()
for i in range(len(data.columns)):
  m[i] = data.columns[i]
for i in range(0,4):
  for j in range(i,4):
    if j != i:
      plt.scatter(X[:,i],X[:,j],c = kmeans.labels_)
      plt.xlabel(m[i])
      plt.ylabel(m[j])
      plt.show()

"""We can have more stores in the mall which appeal to an older demographic to increase the average expenditure
We can taget the male and female audience with different store based campaigns to inform them of all offers to increase footfall and expenditure

"""

